var path = require('path');

// all routes will be prefixed by this (/load => /foo/load, if you change the value to '/foo')
exports.ROUTE_PREFIX = '/';
// path to Kevoree's Java dependencies
// this jar can be generated by running `mvn install` in kevoree-web-editor root folder
exports.KEV_JAR      = path.resolve('target', 'tools.editor.server-0.0.1-jar-with-dependencies.jar');
// server port
exports.PORT         = 3042;
// once loaded, libraries list will be erased (memory flush) every CLEAR_LIBS ms
exports.CLEAR_LIBS   = 1000*60*30; // 30 minutes
